name: CI

on:
  push:
    branches: [ main ]
  # FIX: Triggers on all pull requests for comprehensive testing.
  pull_request:
  workflow_dispatch:

# Centralize versions here for consistency.
env:
  CUDA_VERSION: '11.8.0'
  CATCH2_VERSION: '3.6.0'

jobs:
  #################################################################
  # JOB 1: Build and run C++ tests on Linux and Windows           #
  #################################################################
  build-and-test:
    name: C++ Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Cache Catch2
        uses: actions/cache@v4
        id: cache-catch2
        with:
          path: |
            ${{ runner.os == 'Linux' && '/usr/local/lib/cmake/Catch2' || '' }}
            ${{ runner.os == 'Linux' && '/usr/local/include/catch2' || '' }}
            ${{ runner.os == 'Windows' && 'C:/Program Files (x86)/Catch2' || '' }}
          key: catch2-${{ env.CATCH2_VERSION }}-${{ runner.os }}

      # --- FIX: Use different, more robust installation strategies per OS ---
      - name: Install CUDA Toolkit (Linux)
        if: runner.os == 'Linux'
        uses: Jimver/cuda-toolkit@v0.2.25
        with:
          cuda: ${{ env.CUDA_VERSION }}
          # 'network' method is more robust on Linux as it uses apt.
          method: 'network'

      - name: Install CUDA Toolkit (Windows)
        if: runner.os == 'Windows'
        uses: Jimver/cuda-toolkit@v0.2.25
        with:
          cuda: ${{ env.CUDA_VERSION }}
          method: 'local'
          # Disable the action's internal cache on Windows to prevent path errors.
          use-local-cache: 'false'

      - name: Install Catch2 (Linux)
        if: runner.os == 'Linux' && steps.cache-catch2.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential
          git clone --depth 1 -b v${{ env.CATCH2_VERSION }} https://github.com/catchorg/Catch2.git ~/catch2
          cmake -S ~/catch2 -B ~/catch2/build -DBUILD_TESTING=OFF -DCATCH_INSTALL_DOCS=OFF
          sudo cmake --build ~/catch2/build --target install
          sudo ldconfig

      - name: Install Catch2 (Windows)
        if: runner.os == 'Windows' && steps.cache-catch2.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          git clone --depth 1 -b v${{ env.CATCH2_VERSION }} https://github.com/catchorg/Catch2.git $env:USERPROFILE\catch2
          cmake -S $env:USERPROFILE\catch2 -B $env:USERPROFILE\catch2\build -DBUILD_TESTING=OFF -DCATCH_INSTALL_DOCS=OFF
          cmake --build $env:USERPROFILE\catch2\build --config Release --target install

      - name: Configure and Build
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON -DBUILD_DOCS=OFF
          cmake --build build --parallel --config Debug

      - name: Run C++ Tests
        working-directory: build
        run: ctest --output-on-failure --parallel --config Debug

  #################################################################
  # JOB 2: Build and run Python package tests                     #
  #################################################################
  python-testing:
    name: Python Tests on ${{ matrix.os }} (Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [ "3.11" ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Install CUDA Toolkit (Linux)
        if: runner.os == 'Linux'
        uses: Jimver/cuda-toolkit@v0.2.25
        with:
          cuda: ${{ env.CUDA_VERSION }}
          method: 'network'

      - name: Install CUDA Toolkit (Windows)
        if: runner.os == 'Windows'
        uses: Jimver/cuda-toolkit@v0.2.25
        with:
          cuda: ${{ env.CUDA_VERSION }}
          method: 'local'
          use-local-cache: 'false'

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install and Test Python Package
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt
          python -m pip install -v -e .
          pytest

  #################################################################
  # JOB 3: Run coverage tests on Linux                          #
  #################################################################
  coverage-test:
    name: Coverage Report
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y lcov

      - name: Install CUDA Toolkit
        uses: Jimver/cuda-toolkit@v0.2.25
        with:
          cuda: ${{ env.CUDA_VERSION }}
          method: 'network'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt pytest-cov

      - name: Configure and Build with Coverage Flags
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Debug \
            -DBUILD_TESTING=ON \
            -DBUILD_DOCS=OFF \
            -DCMAKE_CXX_FLAGS="--coverage" \
            -DCMAKE_C_FLAGS="--coverage"
          cmake --build build --parallel

      - name: Run C++ Tests
        working-directory: build
        run: ctest --output-on-failure || true

      - name: Install Python Package with Coverage
        run: |
          export CMAKE_ARGS="-DCMAKE_C_FLAGS=--coverage -DCMAKE_CXX_FLAGS=--coverage"
          python -m pip install -v -e .

      - name: Run Python tests and generate XML report
        run: pytest --cov=. --cov-report=xml

      - name: Generate C++ Coverage Report (lcov)
        run: |
          lcov --capture --directory build --output-file coverage.info
          lcov --remove coverage.info '/usr/*' '*/tests/*' '*/build/*' --output-file coverage_filtered.info

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          verbose: true